### ISSUE TITLE
Issue on Dolibarr Docker image version

### ISSUE THREAD

**Issue by florianblanchet** [soerenmetje/docker-traefik-dolibarr#1]
Hello, thank you for your repository !
For the record I had an error on the docker image of dolibarr in the `dolibarr/docker-compose.yml` file.

`ERROR: manifest for tuxgasy/dolibarr:9.0.4-php7.1 not found: manifest unknown: manifest unknown`

 It seems that the `9.0.4-php7.1 ` is not available anymore. Should be updated to tuxgasy/dolibarr to be correct even if there are new versions of the image or php.

**Comment by soerenmetje** [comment]
Hi! Thank you for your contribution! 
That's right, I fixed the version tag. This setup may not work with future latest releases. So I like to keep tags for now.
